### ISSUE TITLE
Error importing dataset at cartodbfy

### ISSUE THREAD

**Issue by jsanz** [CartoDB/cartodb-postgresql#126]
I can use ogr2ogr with a free account 

``` 
ogr2ogr --config CARTODB_API_KEY BLAH -nln barriosSHP  -s_srs "EPSG:4326" -t_srs "EPSG:4326" -f "CartoDB" "CartoDB:xurxosanz" barrios.shp
```

But I can't do the same with an account at the `team` organization, running the last version of the extension. This get stuck

```
ogr2ogr --config CARTODB_API_KEY BLAH -nln barriosSHP -s_srs "EPSG:4326" -t_srs "EPSG:4326" -f "CartoDB" "CartoDB:solutions" barrios.shp
```

But if I run it without specifying a SRS (the SHP doesn't have a `prj`) file then it finishes with a warning saying:

```
Warning 1: Cannot register table in dashboard with cdb_cartodbfytable() since its SRS is not EPSG:4326
```

I'm running `ogr2ogr` coming from [gisinternals](http://www.gisinternals.com/development.php), the `release-1800-gdal-mapserver` refering to this [commit](https://github.com/mapserver/mapserver/commit/60bd48e66e1d0a9883ba7c5e91eedef039c766bd).

cc. @pramsey

**Comment by pramsey** [comment]
what's the `ogr2ogr --version` ?

**Comment by jsanz** [comment]
```ogr2ogr --version
GDAL 2.1.0dev, released 2015/99/99```

**Comment by rafatower** [comment]
for the record, gdal version: [r29819](https://trac.osgeo.org/gdal/changeset/29819)

**Comment by rafatower** [comment]
I made some tests with this input files:
* barrios.shp
  - polygons
  - 88 features
  - 104 KB

* stations.shp
  - points
  - 11K features
  - 324 KB

and got these results against these accounts:
* rtorre3
  - cartodb-postgresql extension v 0.8.2
  - 1 table
  - barrios: 3.757s
  - stations: 56.387s

* rtorre2
  - cartodb-postgresql extension v 0.9.2
  - 6 table
  - barrios: 3.978s
  - stations: 59.730s

As @rochoa pointed out in a mail thread, seems like we have a performance degradation because of the quota trigger, but there's almost no difference in that regards between v0.8.2 and v0.9.2. The ultimate test would be to rollback in team to v0.8.2 and repeat the experiment.

**Comment by rafatower** [comment]
The current workaround for this is using the `CARTODBFY=NO` layer option and then running the `SELECT CDB_CartodbfyTable()` after the import.

**Comment by rafatower** [comment]
With my team account, after the tweak above:
```
$ time ogr2ogr2 --config CARTODB_API_KEY abcdef123 -nln barriosSHP -s_srs "EPSG:4326" -t_srs "EPSG:4326" -f "CartoDB" "CartoDB:rtorre" barrios.shp
real    0m25.303s
user    0m0.172s
sys     0m0.020s
```
