### ISSUE TITLE
Make cdb_analysis_catalog content be dumpable and restoreable

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb-postgresql#276]
We only care about schema on pg_dump/restore.

cc @zenitraM

**Comment by zenitraM** [comment]
The cause for this was the varying column order we introduced on one of the migrations on 064b26ccd327bf079a9d25f9ed2fe79c2c742bae, in particular, the `username` field.

As we added the username on the last column for new extension installs but on a different one on upgrades, this caused the column order not be always the same. (position 1 or 10).

pg_dump does not include the extension source (so this table's schema is not included on the dump) but does include this contents, using a COPY without column names by default and failing due to the order difference.
