### ISSUE TITLE
Clearly communicate compatible postgresql version

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb-postgresql#328]
With the introduction of the new CDB_QuantileBins, this extension is only compatible with postgresql versions 9.4+. There may be other features like being marked parallel which break backwards compatibility. 

It would save users some headaches (for example https://github.com/CartoDB/cartodb-postgresql/commit/39998a9c88e788d1982f468427531f7314e039ed#r28723290) if there was a version check that aborted the install and communicated the supported versions if the pg version is not supported.

**Comment by andy-esch** [comment]
cc @Algunenano

**Comment by Algunenano** [comment]
Being marked PARALLEL shouldn't affect since it's dropped for non compatible releases, so we could simply update the [dependencies])(https://github.com/CartoDB/cartodb-postgresql/blob/master/README.md#dependencies) in the README.
Although that would be enough I think we should be running the CI with whatever PG releases we want to support.

**Comment by andy-esch** [comment]
100% on the CI for PG releases. I'll do a quick PR to update the README
