### ISSUE TITLE
Jenks Bins fails to produce 3 bins for 3 values

### ISSUE THREAD

**Issue by strk** [CartoDB/cartodb-postgresql#7]
https://documentation.cartodb.com/api/v1/sql?q=SELECT%20CDB_JenksBins%28ARRAY[1,2,3],%203%29

\cc @javisantana

**Comment by inigomedina** [comment]
I'm closing this issue because it has been inactive for a long time. This probably means that it is not reproducible or it has been fixed in a newer version. If it's an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue.

Thank you!
